name: Release all external dictionaries

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - .gitignore
      - README.md
      - TODO.md
      - LICENSE

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: false
  
jobs:
  build:
    # Only builds if commit message contains BUILD
    #if: "contains(github.event.head_commit.message, 'BUILD')"

    runs-on: ubuntu-18.04

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: 'recursive'

    - name: Setup Wine32
      run: |
        ./bin/install_wine32.sh


    - name: Setup Ubuntu packages
      run: |
        ./bin/install_linux_packages.sh 
        # Call a script so that it can be used in a shell/container as well

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        
    - name: Setup Python packages
      run: |
        pip install -r ./requirements.txt

    - name: Build all dictionaries
      run: |
        INPUT_DIR=./ext-dict &&
        OUTPUT_DIR=./ext-output &&
        python ./bin/convert_all.py --input_folder=$INPUT_DIR --output_folder=$OUTPUT_DIR --extension=tab

    - name: Zip all artifacts for release
      run: |
        INPUT_DIR=./ext-dict &&
        OUTPUT_DIR=./ext-output &&
        rm -f $OUTPUT_DIR/*.zip &&
        zip -9 -j $OUTPUT_DIR/all-stardict.zip $OUTPUT_DIR/stardict/*.* &&
        zip -9 -j $OUTPUT_DIR/all-epub.zip     $OUTPUT_DIR/epub/*.*     &&
        zip -9 -j $OUTPUT_DIR/all-kobo.zip     $OUTPUT_DIR/kobo/*.*     &&
        zip -9 -j $OUTPUT_DIR/all-lingvo.zip   $OUTPUT_DIR/lingvo/*.*   &&
        zip -9 -j $OUTPUT_DIR/all-kindle.zip   $OUTPUT_DIR/kindle/*.*

    # - name: Build Kindle .mobi dictionaries
    #   run: |
    #     ./bin/createallhtml.sh &&
    #     ./bin/createallhtml-inflections.sh &&
    #     ./bin/createallmobi.sh
        
    # - name: Build StarDict dictionaries
    #   run: |
    #     ./bin/convert2dict.sh

    # - name: Build Epub dictionaries
    #   run: |
    #     ./bin/convert2epub.sh

    # - name: Build Kobo dictionaries
    #   run: |
    #     ./bin/convert2kobo.sh

    # - name: Build Lingvo dictionaries
    #   run: |
    #     ./bin/convert2lingvo.sh

    - name: Create a new release draft
      id: create_release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "./ext-output/*.zip,./ext-output/kindle/*.mobi,./ext-output/kobo/*.zip,./ext-output/lingvo/*.dz,./ext-output/epub/*.epub"
          body: If you can read this, we have forgotten to fill in the changelog. Sorry!
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          draft: true
          name: External Release ${{ github.ref }}
