name: Release all dictionaries

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
    
jobs:
  build:
    # Only builds if commit message contains BUILD
    if: "contains(github.event.head_commit.message, 'BUILD')"

    runs-on: ubuntu-18.04

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Get submodules
      run: |
        git submodule init &&
        git submodule update

    - name: Setup Wine32
      run: |
        ./bin/install_wine32.sh

    - name: Setup Ubuntu packages
      run: |
        ./bin/install_linux_packages.sh

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        
    - name: Setup Python packages
      run: |
        pip install -r ./bin/requirements.txt

    - name: Build Kindle .mobi dictionaries
      run: |
        ./bin/createallhtml.sh &&
        ./bin/createallhtml-inflections.sh &&
        ./bin/createallmobi.sh
        
    - name: Build StarDict dictionaries
      run: |
        ./bin/convert2dict.sh

    - name: Build Epub dictionaries
      run: |
        ./bin/convert2epub.sh

    - name: Build Kobo dictionaries
      run: |
        ./bin/convert2kobo.sh

    - name: Build Lingvo dictionaries
      run: |
        ./bin/convert2lingvo.sh

    - name: Create a new release draft
      id: create_release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "./output/*.zip,./output/kindle/*.mobi,./output/kobo/*.zip,./output/lingvo/*.dz,./output/epub/*.epub"
          body: If you can read this, we have forgotten to fill in the changelog. Sorry!
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          draft: true
          name: Release ${{ github.ref }}
