name: Release all dictionaries

on:
  workflow_dispatch:

  push:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:

    - uses: actions/checkout@v3

    - name: Setup Wine32
      run: |
        ./bin/install_wine32.sh
        
    # - name: Setup Wine32
    #   run: |
    #     sudo apt install -f aptitude

    #     sudo apt-get install --allow-downgrades libpcre2-8-0=10.34-7
    #     sudo apt-get install --allow-downgrades libssl1.1=1.1.1f-1ubuntu2.1
    #     sudo apt-get install --allow-downgrades libssl1.1:i386=1.1.1f-1ubuntu2.1

    #     sudo aptitude install wine32

    - name: Setup Ubuntu packages
      run: |
        ./bin/install_linux_packages.sh

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        
    - name: Setup Python packages
      run: |
        pip install -r ./bin/requirements.txt

    - name: Build Kindle .mobi dictionaries
      run: |
        ./bin/createallhtml.sh
        ./bin/createallhtml-inflections.sh
        ./bin/createallmobi.sh
        
    - name: Build StarDict dictionaries
      run: |
        ./bin/convert2dict.sh

    - name: Build Epub dictionaries
      run: |
        ./bin/convert2epub.sh

    - name: Build Kobo dictionaries
      run: |
        ./bin/convert2kobo.sh

    - name: Build Lingvo dictionaries
      run: |
        ./bin/convert2lingvo.sh

    - name: Create a new release draft
      id: create_release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "./output/*.*,./output/kindle/*.*,./output/kobo/*.*,./output/lingvo/*.*,./output/epub/*.*"
          body: If you can read this, we have forgotten to fill in the changelog. Sorry!
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          draft: true
          name: Release ${{ github.ref }}
