name: Release all INTERNAL & EXTERNAL dictionaries

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - .gitignore
      - '*.md'
      - LICENSE
      - bin/create_inflections.py      

env:
  INPUT_DIR: ./ext-dict
  OUTPUT_DIR: ./ext-output

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: false
  
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'AUTO')"

    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: 'recursive'

    - name: Setup Ubuntu packages
      run: |
        # Call a script so that it can be used in a shell/container as well
        ./bin/install_linux_packages.sh 

    - name: Setup Wine32
      run: |
        # Call a script so that it can be used in a shell/container as well
        ./bin/install_wine32.sh

    - name: Setup Utilities
      run: |
        # Call a script so that it can be used in a shell/container as well
        ./bin/install_utilities.sh

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        
    - name: Setup Python packages
      run: |
        pip install -r ./requirements.txt

    - name: Copy internal dictionaries
      run: |
        cp dict/*.* $INPUT_DIR/ &&
        ls $INPUT_DIR

    - name: Build all dictionaries
      run: |
        python ./bin/convert_all.py --input_folder=$INPUT_DIR --output_folder=$OUTPUT_DIR --extension=tab

    - name: Zip all artifacts for release
      run: |
        zip -9 -j $OUTPUT_DIR/all-stardict.zip $OUTPUT_DIR/stardict/*.*      &&
        zip -9 -j $OUTPUT_DIR/all-epub.zip     $OUTPUT_DIR/epub/*.*          &&
        zip -9 -j $OUTPUT_DIR/all-kobo.zip     $OUTPUT_DIR/kobo/*.*          &&
        zip -9 -j $OUTPUT_DIR/all-lingvo.zip   $OUTPUT_DIR/lingvo/*.*        &&
        zip -9 -j $OUTPUT_DIR/all-kindle.zip   $OUTPUT_DIR/kindle/*.*        &&
        zip -9 -j $OUTPUT_DIR/all-dictd.zip    $OUTPUT_DIR/dictd/*.*         &&
        zip -9 -j $OUTPUT_DIR/all-yomitan.zip  $OUTPUT_DIR/yomitan/*.*  &&
        ls -R -l $OUTPUT_DIR

    - name: Create a new release draft
      id: create_release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "./ext-output/*.zip,./ext-output/kindle/*.mobi,./ext-output/kobo/*.zip,./ext-output/lingvo/*.dz,./ext-output/epub/*.epub,./output/yomitan/*.zip"
          body: If you can read this, we have forgotten to fill in the changelog. Sorry!
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          draft: true
          name: External Release ${{ github.ref }}
